
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- 404 Error Text -->
    <div class="text-center">
        <div class="error mx-auto" data-text="403">403</div>
        <p class="lead text-gray-800 mb-5">Você não tem permissão para acessar essa tela.</p>
        <p class="text-gray-500 mb-0">Parece que você encontrou uma falha na matriz...</p>
        <a href="/">&larr; Voltar para tela inicial</a>
    </div>
</div>